### ISSUE TITLE
Add support of rubocop extensions

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE-QA/convert-service-testing#149]
Add support of `rubocop-rspec` and `rubocop-performance` gems

Similar like [this](https://github.com/ONLYOFFICE-QA/onlyoffice_s3_wrapper/pull/21) or [this](https://github.com/ONLYOFFICE/ooxml_parser/pull/608/files)

I'm sure some of new issues by `rubocop-rspec` will be pretty hard to fix, but there will be plenty of `auto-fixed` issues, at least fix them

**Comment by askonev** [comment]
https://github.com/ONLYOFFICE-QA/convert-service-testing/commit/5e552336826618ef12c17618c63679d4b9127799
